"""add timezone line

Revision ID: 1a687dfa6883
Revises: 2848507dd97d
Create Date: 2025-05-26 16:07:36.573558

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1a687dfa6883"
down_revision: Union[str, None] = "2848507dd97d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("patients", sa.Column("timezone", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("patients", "timezone")
    # ### end Alembic commands ###
